version: '3'
services:
  e2e-cypress:
    image: "cypress/included:9.5.1"
    container_name: "e2e-cypress-learning"
    user: "${UID}:${GID}"
    environment:
      - CYPRESS_baseUrl=https://employer.wuzzuf.basharsys.com
      - DISPLAY
    entrypoint: ["cypress","open", "--project","."]
    working_dir: "/e2e"
    volumes:
      - ./e2e:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.X11-unix:/tmp/.X11-unix
